// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	GetPostById(ctx context.Context, id int64) (Post, error)
	ListPosts(ctx context.Context) ([]Post, error)
}

var _ Querier = (*Queries)(nil)
